logging:
  file:
    enable: true
    level: INFO
    path: logs
    rotation: "10 MB"
    retention: "7 days"
  console:
    enable: true
    level: INFO

db_meta:
  host: 82.156.200.4
  port: 3306
  user: atguigu
  password: Atguigu.123
  database: meta

db_dw:
  host: 82.156.200.4
  port: 3306
  user: atguigu
  password: Atguigu.123
  database: dw

qdrant:
  host: 82.156.200.4
  port: 6333
  embedding_size: 1024

embedding:
  host: localhost
  port: 11434
  model: qwen3-embedding:4b


es:
  host: 82.156.200.4
  port: 9200
  index_name: data_agent


llm:
  model_name: gpt-5.2-codex
  api_key: <api-key>
  base_url: https://api.openai-proxy.org/v1

siliconFlow_embedding:
  base_url: https://api.siliconflow.cn/v1
  model: BAAI/bge-large-zh-v1.5
  token: sk-isjclcfkxewxtilnhsejwszghbwirhhprmdcraknmsnuqtzr
  embedding_size: 1024

milvus:
  host: localhost
  port: 19530
  token: root:Milvus
  collection_name: test_data_agent
  embedding_size: 1024